version: "2"
services:
  neuroscout:
    image: ghcr.io/neuroscout/neuroscout:latest
    volumes:
      - ./neuroscout/config/app.py:/usr/src/app/neuroscout/config/app.py
      - frontend_build:/usr/src/app/neuroscout/frontend/build

  nginx:
    volumes:
      - frontend_build:/usr/src/app/neuroscout/frontend/build


volumes:
    frontend_build: