version: "3"
services:
  neuroscout:
    image: ghcr.io/neuroscout/neuroscout:${IMAGE_TAG}
    volumes:
      - ./neuroscout:/usr/src/app/neuroscout
  resources:
    reservations:
      devices:
        - driver: nvidia
          capabilities: [gpu]


  nginx:
    volumes:
      - ./neuroscout/frontend/build:/usr/src/app/neuroscout/frontend/build
