"""empty message

Revision ID: 05df5e3a41f3
Revises: d4417864ab88
Create Date: 2019-08-30 16:32:39.066853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05df5e3a41f3'
down_revision = 'd4417864ab88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neurovault_file_upload')
    op.add_column('neurovault_collection', sa.Column('status', sa.Text(), nullable=True))
    op.add_column('neurovault_collection', sa.Column('task_id', sa.Text(), nullable=True))
    op.add_column('neurovault_collection', sa.Column('traceback', sa.Text(), nullable=True))
    op.drop_constraint('neurovault_collection_collection_id_key', 'neurovault_collection', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('neurovault_collection_collection_id_key', 'neurovault_collection', ['collection_id'])
    op.drop_column('neurovault_collection', 'traceback')
    op.drop_column('neurovault_collection', 'task_id')
    op.drop_column('neurovault_collection', 'status')
    op.create_table('neurovault_file_upload',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nv_collection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exception', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("level = ANY (ARRAY['GROUP'::text, 'SUBJECT'::text])", name='neurovault_file_upload_level_check'),
    sa.CheckConstraint("status = ANY (ARRAY['OK'::text, 'FAILED'::text, 'PENDING'::text])", name='neurovault_file_upload_status_check1'),
    sa.ForeignKeyConstraint(['nv_collection_id'], ['neurovault_collection.id'], name='neurovault_file_upload_nv_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='neurovault_file_upload_pkey')
    )
    # ### end Alembic commands ###
