"""empty message

Revision ID: 0a774092a8ae
Revises: c0e7af15c79d
Create Date: 2020-11-12 16:31:31.551643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a774092a8ae'
down_revision = 'c0e7af15c79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neurovault_collection', sa.Column('cli_version', sa.Text(), nullable=True))
    op.add_column('neurovault_collection', sa.Column('fmriprep_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('neurovault_collection', 'fmriprep_version')
    op.drop_column('neurovault_collection', 'cli_version')
    # ### end Alembic commands ###
