"""empty message

Revision ID: 14645812442b
Revises: 3c220a63857e
Create Date: 2020-06-03 21:53:13.345183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14645812442b'
down_revision = '3c220a63857e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('stim_run', 'run_stimulus', ['stimulus_id', 'run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stim_run', table_name='run_stimulus')
    # ### end Alembic commands ###
