"""empty message

Revision ID: 2474c993e37a
Revises: 9863aebba611
Create Date: 2018-09-20 17:35:57.223833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2474c993e37a'
down_revision = '9863aebba611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('compile_task_id', sa.Text(), nullable=True))
    op.drop_column('analysis', 'celery_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('celery_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('analysis', 'compile_task_id')
    # ### end Alembic commands ###
