"""empty message

Revision ID: 2685cfc2f8b7
Revises: 3dcd7657d563
Create Date: 2019-06-27 22:04:02.030608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2685cfc2f8b7'
down_revision = '3dcd7657d563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('open_tour', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'open_tour')
    # ### end Alembic commands ###
