"""empty message

Revision ID: 2e44c02f1626
Revises: 3589454505cb
Create Date: 2018-07-23 20:14:29.281164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e44c02f1626'
down_revision = '3589454505cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_feature', sa.Column('original_name', sa.String(), nullable=True))
    op.add_column('predictor', sa.Column('original_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictor', 'original_name')
    op.drop_column('extracted_feature', 'original_name')
    # ### end Alembic commands ###
