"""empty message

Revision ID: 3c220a63857e
Revises: f4000ac8797c
Create Date: 2020-01-23 23:16:37.520188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c220a63857e'
down_revision = 'f4000ac8797c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'warnings')
    # ### end Alembic commands ###
