"""empty message

Revision ID: 3dcd7657d563
Revises: 9efb0d7634e3
Create Date: 2019-05-22 19:23:56.537827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcd7657d563'
down_revision = '9efb0d7634e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.add_column('analysis', sa.Column('traceback', sa.Text(), nullable=True))
    op.drop_column('analysis', 'compile_traceback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('compile_traceback', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('analysis', 'traceback')
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], name='result_analysis_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='result_pkey')
    )
    # ### end Alembic commands ###
