"""empty message

Revision ID: 3fedbc6e3973
Revises: 5cf42e00634a
Create Date: 2019-09-13 21:17:41.075663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fedbc6e3973'
down_revision = '5cf42e00634a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_predictor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_predictor',
    sa.Column('pc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predictor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pc_id'], ['predictor_collection.id'], name='collection_predictor_pc_id_fkey'),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictor.id'], name='collection_predictor_predictor_id_fkey')
    )
    # ### end Alembic commands ###
