"""empty message

Revision ID: 5cf42e00634a
Revises: 8dedbfca852e
Create Date: 2019-09-13 21:14:08.084208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf42e00634a'
down_revision = '8dedbfca852e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictor', sa.Column('predictor_collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predictor', 'predictor_collection', ['predictor_collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predictor', type_='foreignkey')
    op.drop_column('predictor', 'predictor_collection_id')
    # ### end Alembic commands ###
