"""empty message

Revision ID: 8324c6661b5a
Revises: 0c7b8157b950
Create Date: 2018-09-20 23:25:49.534125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8324c6661b5a'
down_revision = '0c7b8157b950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('traceback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'traceback')
    # ### end Alembic commands ###
