"""empty message

Revision ID: 88f313fe1de5
Revises: 2e44c02f1626
Create Date: 2018-07-26 02:16:11.851221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f313fe1de5'
down_revision = '2e44c02f1626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_feature', sa.Column('transformed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_feature', 'transformed')
    # ### end Alembic commands ###
