"""empty message

Revision ID: 8a4450817d65
Revises: ef770354e712
Create Date: 2020-06-29 21:58:32.560292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4450817d65'
down_revision = 'ef770354e712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('institution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'institution')
    # ### end Alembic commands ###
