"""empty message

Revision ID: 8dedbfca852e
Revises: 398589c37576
Create Date: 2019-09-03 20:35:42.946524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dedbfca852e'
down_revision = '398589c37576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictor', sa.Column('private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictor', 'private')
    # ### end Alembic commands ###
