"""empty message

Revision ID: 9863aebba611
Revises: 80cf7f342ff8
Create Date: 2018-09-14 21:47:30.683843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9863aebba611'
down_revision = '80cf7f342ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'summary')
    op.drop_column('dataset', 'url')
    # ### end Alembic commands ###
