"""empty message

Revision ID: 992efb03fa6d
Revises: 8a4450817d65
Create Date: 2020-07-09 14:31:55.940588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992efb03fa6d'
down_revision = '8a4450817d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_event', 'history')
    op.add_column('user', sa.Column('orcid', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('personal_site', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('public_email', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('twitter_handle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_handle')
    op.drop_column('user', 'public_email')
    op.drop_column('user', 'personal_site')
    op.drop_column('user', 'orcid')
    op.add_column('extracted_event', sa.Column('history', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
