"""empty message

Revision ID: 9d511bb80efc
Revises: 992efb03fa6d
Create Date: 2020-08-12 14:49:57.747304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d511bb80efc'
down_revision = '992efb03fa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'user', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
