"""empty message

Revision ID: 9efb0d7634e3
Revises: c189d593576d
Create Date: 2019-03-19 23:22:55.805114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efb0d7634e3'
down_revision = 'c189d593576d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neurovault_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Text(), nullable=True),
    sa.Column('collection_id', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'FAILED', 'PENDING')"),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.hash_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('run', 'func_path')
    op.drop_column('run', 'mask_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('mask_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('run', sa.Column('func_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('neurovault_collection')
    # ### end Alembic commands ###
