"""empty message

Revision ID: a5e1fbca2504
Revises: 
Create Date: 2018-07-18 16:06:53.379572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e1fbca2504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_predictor_event_predictor_id'), 'predictor_event', ['predictor_id'], unique=False)
    op.create_index(op.f('ix_predictor_event_run_id'), 'predictor_event', ['run_id'], unique=False)
    op.create_index('ix_predictor_id_run_id', 'predictor_event', ['predictor_id', 'run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictor_id_run_id', table_name='predictor_event')
    op.drop_index(op.f('ix_predictor_event_run_id'), table_name='predictor_event')
    op.drop_index(op.f('ix_predictor_event_predictor_id'), table_name='predictor_event')
    # ### end Alembic commands ###
