"""empty message

Revision ID: ad787307f461
Revises: 2685cfc2f8b7
Create Date: 2019-06-27 23:06:44.185953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad787307f461'
down_revision = '2685cfc2f8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_login', sa.Boolean(), nullable=True))
    op.drop_column('user', 'open_tour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('open_tour', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'first_login')
    # ### end Alembic commands ###
