"""empty message

Revision ID: c0e7af15c79d
Revises: fc2bbd3e5824
Create Date: 2020-11-12 01:08:09.735081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e7af15c79d'
down_revision = 'fc2bbd3e5824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_feature', sa.Column('resample_frequency', sa.Float(), nullable=True))
    op.drop_column('neurovault_collection', 'fmriprep_version')
    op.drop_column('neurovault_collection', 'cli_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neurovault_collection', sa.Column('cli_version', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('neurovault_collection', sa.Column('fmriprep_version', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('extracted_feature', 'resample_frequency')
    # ### end Alembic commands ###
