"""empty message

Revision ID: c189d593576d
Revises: a52d71d9d9e0
Create Date: 2019-01-30 17:19:04.958404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c189d593576d'
down_revision = 'a52d71d9d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictor', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictor', 'active')
    # ### end Alembic commands ###
