"""empty message

Revision ID: cf36d903b9d6
Revises: 0af7b25b2d83
Create Date: 2020-06-04 19:45:56.495752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf36d903b9d6'
down_revision = '0af7b25b2d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ef_id', 'extracted_event', ['ef_id'], unique=False)
    op.drop_index('stim_run', table_name='run_stimulus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('stim_run', 'run_stimulus', ['run_id', 'stimulus_id'], unique=False)
    op.drop_index('idx_ef_id', table_name='extracted_event')
    # ### end Alembic commands ###
