"""empty message

Revision ID: d4417864ab88
Revises: 5105cfcc9c86
Create Date: 2019-08-29 20:33:30.573981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4417864ab88'
down_revision = '5105cfcc9c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neurovault_file_upload', sa.Column('exception', sa.Text(), nullable=True))
    op.add_column('neurovault_file_upload', sa.Column('path', sa.Text(), nullable=False))
    op.add_column('neurovault_file_upload', sa.Column('traceback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('neurovault_file_upload', 'traceback')
    op.drop_column('neurovault_file_upload', 'path')
    op.drop_column('neurovault_file_upload', 'exception')
    # ### end Alembic commands ###
