"""empty message

Revision ID: eaf39d8e9d94
Revises: 3fedbc6e3973
Create Date: 2019-10-16 22:12:31.706646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf39d8e9d94'
down_revision = '3fedbc6e3973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('known_issues', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'known_issues')
    # ### end Alembic commands ###
