"""empty message

Revision ID: ef770354e712
Revises: cf36d903b9d6
Create Date: 2020-06-24 20:24:55.275971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef770354e712'
down_revision = 'cf36d903b9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('sampling_rate', sa.Float(), nullable=True))
    op.add_column('report', sa.Column('scale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'scale')
    op.drop_column('report', 'sampling_rate')
    # ### end Alembic commands ###
