"""empty message

Revision ID: f4000ac8797c
Revises: eaf39d8e9d94
Create Date: 2020-01-22 22:07:02.107399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4000ac8797c'
down_revision = 'eaf39d8e9d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('long_description', sa.Text(), nullable=True))
    op.drop_column('dataset', 'known_issues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('known_issues', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('dataset', 'long_description')
    # ### end Alembic commands ###
