"""empty message

Revision ID: fa02cc560c61
Revises: 14645812442b
Create Date: 2020-06-03 22:25:38.039770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa02cc560c61'
down_revision = '14645812442b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stim_run', table_name='run_stimulus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('stim_run', 'run_stimulus', ['stimulus_id', 'run_id'], unique=False)
    # ### end Alembic commands ###
