studyforrest_phase2:
  path: https://github.com/psychoinformatics-de/studyforrest-data-phase2.git
  tasks:
    objectcategories:
      features:
        - default.json
      filters:
        subject: "01"
        run: 1
