FROM python:3.6-onbuild
RUN wget -qO- https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install nodejs -y
RUN apt-get install apt-transport-https -y
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -y
RUN apt-get install yarn -y
RUN bash scripts/build_static.sh
RUN bash scripts/copy_static.sh
